
esercizio5.5: esercizio5.5.o lib5.5/gplot++.h lib5.5/tests.h lib5.5/field.h lib5.5/mat_point.h lib5.5/point.h lib5.5/physics.h lib5.5/particle.h
	g++  -o esercizio5.5 esercizio5.5.o       

esercizio5.5.o: esercizio5.5.cpp
	g++  -std=c++20 -c esercizio5.5.cpp

clean:
	rm esercizio5.5 esercizio5.5.o
