
esercizio8.1: esercizio8.1.o lib8.1/test_geom.h lib8.1/test_diff_eq.h lib8.1/gplot++.h
	g++  -o esercizio8.1 esercizio8.1.o   

esercizio8.1.o: esercizio8.1.cpp
	g++   -c esercizio8.1.cpp

clean:
	rm esercizio8.1 esercizio8.1.o
