
esercizio11.1: esercizio11.1.o lib11.1/experiments.h lib11.1/gplot++.h lib11.1/test_random.h lib11.1/test_stats.h
	g++  -o esercizio11.1 esercizio11.1.o    

esercizio11.1.o: esercizio11.1.cpp
	g++  -std=c++20 -c esercizio11.1.cpp

clean:
	rm esercizio11.1 esercizio11.1.o
