
esercizio8.3: esercizio8.3.o lib8.3/diff_eq.h lib8.3/geom.h lib8.3/gplot++.h lib8.3/test_diff_eq.h lib8.3/test_geom.h lib8.3/vect_function.h
	g++  -o esercizio8.3 esercizio8.3.o      

esercizio8.3.o: esercizio8.3.cpp
	g++   -c esercizio8.3.cpp

clean:
	rm esercizio8.3 esercizio8.3.o
