
esercizio7.3: esercizio7.3.o lib7.3/gplot++.h lib7.3/integral.h lib7.3/integral_tests.h
	g++  -o esercizio7.3 esercizio7.3.o   

esercizio7.3.o: esercizio7.3.cpp
	g++  -std=c++20 -c esercizio7.3.cpp

clean:
	rm esercizio7.3 esercizio7.3.o
