
esercizio8.5: esercizio8.5.o lib8.5/diff_eq.h lib8.5/geom.h lib8.5/gplot++.h lib8.5/test_diff_eq.h lib8.5/test_geom.h lib8.5/vect_function.h
	g++  -o esercizio8.5 esercizio8.5.o      

esercizio8.5.o: esercizio8.5.cpp
	g++ -std=c++20  -c esercizio8.5.cpp

make esegui: esercizio8.5
	./esercizio8.5

clean:
	rm esercizio8.5 esercizio8.5.o
