
esercizio7.0: esercizio7.0.o lib7.0/gplot++.h lib7.0/integral.h
	g++  -o esercizio7.0 esercizio7.0.o  

esercizio7.0.o: esercizio7.0.cpp
	g++  -std=c++20 -c esercizio7.0.cpp

clean:
	rm esercizio7.0 esercizio7.0.o
