
esercizio10.3: esercizio10.3.o lib10.3/gplot++.h lib10.3/integral_mc.h lib10.3/test_integral_mc.h lib10.3/test_random.h
	g++  -o esercizio10.3 esercizio10.3.o    

esercizio10.3.o: esercizio10.3.cpp
	g++   -c esercizio10.3.cpp

clean:
	rm esercizio10.3 esercizio10.3.o
