esercizio1.3: esercizio1.3.o funzioni.o 
	g++ esercizio1.3.o funzioni.o  -o esercizio1.3

esercizio1.3.o: esercizio1.3.cpp
	g++ -c esercizio1.3.cpp -o esercizio1.3.o
funzioni.o: funzioni.cpp
	g++ -c funzioni.cpp -o funzioni.o

clean:
	rm funzioni.o 
	rm *.o esercizio1.3

