esercizio5.3: esercizio5.3.cpp lib5.3/field.h lib5.3/mat_point.h lib5.3/particle.h lib5.3/point.h lib5.3/atom.h lib5.3/tests.h 
	g++ esercizio5.3.cpp -o esercizio5.3 -std=c++20


clean:
	rm esercizio5.3

