
esercizio10.0: esercizio10.0.o lib10.0/gplot++.h lib10.0/random.h lib10.0/test_random.h
	g++  -o esercizio10.0 esercizio10.0.o   

esercizio10.0.o: esercizio10.0.cpp
	g++   -c esercizio10.0.cpp

clean:
	rm esercizio10.0 esercizio10.0.o
