
esercizio10.1: esercizio10.1.o lib10.1/gplot++.h lib10.1/random.h lib10.1/test_random.h
	g++  -o esercizio10.1 esercizio10.1.o   

esercizio10.1.o: esercizio10.1.cpp
	g++  -std=c++20 -c esercizio10.1.cpp

clean:
	rm esercizio10.1 esercizio10.1.o
