
esercizio8.4: esercizio8.4.o lib8.4/diff_eq.h lib8.4/geom.h lib8.4/gplot++.h lib8.4/test_diff_eq.h lib8.4/test_geom.h lib8.4/vect_function.h
	g++  -o esercizio8.4 esercizio8.4.o      

esercizio8.4.o: esercizio8.4.cpp
	g++   -c esercizio8.4.cpp

clean:
	rm esercizio8.4 esercizio8.4.o
