
esercizio7.1: esercizio7.1.o lib7.1/integral.h lib7.1/tests.h
	g++  -o esercizio7.1 esercizio7.1.o  

esercizio7.1.o: esercizio7.1.cpp
	g++ -std=c++20  -c esercizio7.1.cpp

clean:
	rm esercizio7.1 esercizio7.1.o
