esercizio5.1: esercizio5.1.o lib5.1/particle.h lib5.1/electron.h
	g++ -o esercizio5.1 esercizio5.1.o -std=c++20

esercizio5.1.o: esercizio5.1.cpp
	g++ -c esercizio5.1.cpp -o esercizio5.1.o -std=c++20


clean: 
	rm *.o esercizio5.1

