
esercizio8.6: esercizio8.6.o lib8.6/diff_eq.h lib8.6/geom.h lib8.6/gplot++.h lib8.6/test_diff_eq.h lib8.6/test_geom.h lib8.6/vect_function.h
	g++  -o esercizio8.6 esercizio8.6.o      

esercizio8.6.o: esercizio8.6.cpp
	g++ -std=c++20  -c esercizio8.6.cpp

clean:
	rm esercizio8.6 esercizio8.6.o
