
esercizio7.2: esercizio7.2.o lib7.2/integral.h lib7.2/tests.h
	g++  -o esercizio7.2 esercizio7.2.o  

esercizio7.2.o: esercizio7.2.cpp
	g++  -std=c++20 -c esercizio7.2.cpp

clean:
	rm esercizio7.2 esercizio7.2.o
