CXXFLAGS = -g3 -Wall --pedantic -std=c++23

esercizio3.1: esercizio3.1.o lib3.1/iofunctions.h lib3.1/stats.h lib3.1/tests.h 
	g++ esercizio3.1.cpp  -o esercizio3.1 $(CXXFLAGS)

clean:
	rm esercizio3.1 esercizio3.1.o

