
esercizio6.3: esercizio6.3.o
	g++ -o esercizio6.3 esercizio6.3.o    

esercizio6.3.o: esercizio6.3.cpp lib6.3/functions.h lib6.3/math.h lib6.3/tests.h
	g++ -c esercizio6.3.cpp -std=c++20

clean:
	rm esercizio6.3 esercizio6.3.o
