esercizio1.3: esercizio1.3.o lib1.3/funzioni.o 
	g++ esercizio1.3.o lib1.3/funzioni.o  -o esercizio1.3

esercizio1.3.o: esercizio1.3.cpp
	g++ -c esercizio1.3.cpp -o esercizio1.3.o
lib1.3/funzioni.o: lib1.3/funzioni.cpp
	g++ -c lib1.3/funzioni.cpp -o lib1.3/funzioni.o

clean:
	rm lib1.3/funzioni.o 
	rm *.o esercizio1.3

